@startuml "TSNow_Comp_architecture_summaries"
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth 300
skinparam maxMessageSize 300


Container(home, "Home Screen", "Screen: React Native", "Provides an interface for starting, stoping, selecting, and saving an activity along with notes")

System_Boundary(c1, "Summaries") {
    Container(home, "Home Screen", "Screen: React Native", "Provides an interface for starting, stoping, selecting, and saving an activity along with notes")

    Container(summary, "Summary Screen", "Screen: React Native", "Provides an interface for viewing activity summaries over a period")

    Container(errorsComp, "Errors Component", "Component: React Native", "Component for managing and displaying errors")

    Container(activityStore, "Activity Store", "Store: MobX", "MobX state store; stores and handles all activity based information")

    Container(uiStore, "UI Store", "Store: MobX", "MobX state store; stores application-wide UI state")
}

System_Ext(TS, "Time Study API", "Restful API providing platform's functionality")

Rel(home, summary, "Routes to")

Rel(summary, activityStore, "Uses", "Observer, MobX actions")
Rel(summary, uiStore, "Uses", "Observer, MobX actions")

Rel(errorsComp, uiStore, "Uses", "Observer, MobX actions")

Rel(activityStore, TS, "Makes API calls to", "Async, JSON/HTTPS")

@enduml